print(1+1)
print('a'+'b')
print('1'+'1')
print(int('1'), type(int('1')))
print(int('1')+1)
print(float('1')+1)
print(type(float('1')+1))
print(bool('True'))
print(type(bool('True')))
print(str(11)+'b')
